# Generated by Django 4.2.1 on 2023-06-02 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_oferta_venta_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 17, 18, 33, 707526)),
        ),
    ]
