# Generated by Django 4.2.1 on 2023-06-23 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 16, 29, 28, 57525)),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('nro_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
