# Generated by Django 4.2.1 on 2023-06-23 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_venta_fecha_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 16, 30, 2, 851289)),
        ),
    ]
